### ISSUE TITLE
Any API to Generate CCDA 

### ISSUE THREAD

**Issue by Rajeshkmsc** [jmandel/ccda-to-json#2]
Hi,

 Thanks in advance.
 Help me to find good API to generate CCDA for health care records.

Thanks
Rajesh.k

**Comment by jmandel** [comment]
Well, that's a much more constrained space. The only API-driven approach I'm aware of is [Model-Driven Health Tools](https://www.projects.openhealthtools.org/sf/projects/mdht/), which is a Java platform that can parse C-CDAs and also generate them from an internal object model.

I've often just used string templating, which is far from ideal, but if the shape of your data is very consistent, it can work fine.
