### ISSUE TITLE
offtopic: CCRs and lab results

### ISSUE THREAD

**Issue by mrose17** [jmandel/ccda-to-json#4]
sorry for the noise!

would it be possible to get a pointer to how one encodes lab results via CCR? neither LabCorp nor Quest Diagnostics have a download "CCR" (or "CCD") button, but only a "PDF" button.

fine, i can run http://tabula.technology/ as well as anyone else and clean up the output. and i can write a transformation program ... if i know what the format/dictionary is... would you be able to help?

many thanks!

/mtr

**Comment by jmandel** [comment]
This repo is no longer maintained, but if you're looking for a good data format to represent lab results, please see:

http://hl7-fhir.github.io/observation
http://hl7-fhir.github.io/diagnosticreport

**Comment by mrose17** [comment]
many, many thanks!
